mysite/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from work import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('message/', include('message.urls')),
    path('work/', include('work.urls')),
    path('auth/', include('loginsystem.urls')),
    path('activity', views.activity),
    path('', include('mainApp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/user/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('<int:id>', views.user, name='user_with_id'),
    path('editor/', views.editor)
]

mysite/work/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('<int:id>', views.work, ),
    path('create/', views.create),
    path('like', views.like,),
]

mysite/work/models.py
from django.db import models
from django.contrib.auth.models import User
import os

class Work(models.Model):
    
    class Meta():
        db_table = 'Work'
    name = models.CharField(max_length = 50)
    text = models.TextField()
    photo = models.ImageField(upload_to='works', blank=True, default = None)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mark = models.IntegerField(default=0)
    fio = models.CharField(max_length = 50, blank=True)
    document = models.FileField(upload_to='documents', blank = True)

    def extension(self):
        if not self.document:
            return 'none'
        name, extension = os.path.splitext(self.document.name)
        if extension in ['.3g2', '.3gp', '.3gp2', '.3gpp', '.3gpp2', '.asf', '.asx', '.avi', '.bin',
         '.dat', '.drv', '.f4v', '.flv', '.gtp', '.h264', '.m4v', '.mkv', '.mod', '.moov', '.mov',
          '.mp4', '.mpeg', '.mpg', '.mts', '.rm', '.rmvb', '.spl', '.srt', '.stl', '.swf', '.ts',
           '.vcd', '.vid', '.vob', '.webm', '.wm', '.wmv', '.yuv']:
           return 'video'
        elif extension in ['.wav', '.aif', '.mp3', '.mid']:
            return 'audio'
        else:
            return 'other'

    def __str__(self):
        return self.name

class Like(models.Model):
    class Meta():
        db_table = 'Like'
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.work.name)

mysite/work/forms.py
from django import forms
from .models import Work


class CreateWork(forms.ModelForm):   

    name = forms.CharField(
        label='Название',
        help_text='',
        required=True,
        max_length=50,
    )

    text = forms.TextInput(
    )

    photo = forms.ImageField(
        label='Фотография',
        help_text='',
        required=True,
    )

    document = forms.FileField(
        label='Ваша работа',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(CreateWork, self).__init__(*args, **kwargs)
        self.fields['text'].label = 'Описание'


    class Meta:
        model = Work
        fields = ('name', 'text', 'photo', 'document')

mysite/work/views.py
from django.shortcuts import render,redirect
from django.middleware import csrf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpRequest
from .forms import CreateWork
from .models import Work, Like

def activity(request):
    object_list = Work.objects.all()
    object_list = object_list.order_by("-mark")
    paginator = Paginator(object_list, 8)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    likes = Like.objects.filter(user = request.user.id)
    args = {'list':queryset, 'likes':likes}
    args['csrf_token'] = csrf.get_token(request)
    return render(request,'work/activity.html', args)

def work(request, id=None):
    if id==0:
        id = -1
    if id:
        try:
            work = Work.objects.get(id=id)
            args = {'work':work}
            args['likes'] = Like.objects.filter(user = request.user.id)
            return render(request,'work/work.html', args)
        except:
            args = {'error':True}
            return render(request,'work/work.html', args)
    else:
        return render(request,'work/work.html',args)



def create(request):
    args = {}
    args['csrf_token'] = csrf.get_token(request)
    work = Work()
    form = CreateWork()

    args['form'] = form

    if request.POST:
        post = request.POST
        if request.FILES:
            photo = request.FILES['photo']
            work.name = post.get('name','')
            work.text = post.get('text','')
            if request.user.is_authenticated:
                work.user = request.user
            else:
                work.user = User.objects.get(id=3)
                work.fio = post.get('fio','')
            if request.FILES['document']:
                work.document = request.FILES['document']
            work.save()
            photo.name = str(Work.objects.latest('id').id)+'.jpg'
            work.photo = photo
            work.save()
        return redirect('/work/'+str(Work.objects.latest('id').id))
    return render(request,'work/create.html', args)

@csrf_exempt
def like(request):
    try:
        request.META['HTTP_REFERER']
    except:
        return redirect('/')
    if not request.user.is_authenticated or not request.user.is_staff:
        return HttpResponse(' ')
    else:
        id = request.POST.get('id')
        likes = Like.objects.filter(user = request.user.id)
        if  CheckLike(likes, id):
            r = Work.objects.get(id = id)
            r.mark-=1
            r.save()
            like = Like.objects.filter(user = request.user.id, work = Work.objects.get(id = id))
            like.delete()
        else:
            r = Work.objects.get(id = id)
            r.mark+=1
            r.save()
            like = Like(user = request.user, work = Work.objects.get(id = id))
            like.save()
        return HttpResponse('')

def CheckLike(likes, work):
    for like in likes:
        if work == str(like.work.id):
            return True
    return False

mysite/work/templates/work/activity.html
{% extends "mainApp/wrapper.html" %}
{% block title %}
Список
{% endblock %}

{% block content %}

  <section class="art-list">
    {% for work in list %}

      <div class="art-list__card art-card">
        <div class="art-card__mask"></div>
        <img src="{{work.photo.url}}" alt="{{work.name}}" class="art-card__photo">
        <div class="art-card__descr">
          <a href="/work/{{work.id}}" class="art-card__name">{{work.name}}</a>
          <p class="art-card__text">{{work.text}}</p>
          <div class="art-card__rating">
            <p id="{{work.id}}" {% for like in likes %}{% if like.work.id == work.id %} class="like-added"
              {% endif %}{% endfor %}><i class="fas fa-heart" onclick="like(this)"
                ></i> <span class="mark">{{work.mark}}</span></p>
          </div>
        </div>
      </div>
    {% endfor %}
      <div class="pagination">
        {% if list.has_previous %}
        <a class="pagination__prev-page" href="?page={{ list.previous_page_number }}">Предыдущая</a>
        {% else %}
        <a style="visibility: hidden" class="pagination__prev-page" href="">Предыдущая</a>
        {% endif %}
      
        <span class="pagination__current">{{ list.number }} из {{ list.paginator.num_pages }}</span>
      
        {% if list.has_next %}
        <a class="pagination__next-page" href="?page={{ list.next_page_number }}">Следующая</a>
        {% else %}
        <a style="visibility: hidden" class="pagination__next-page" href="">Следующая</a>
        {% endif %}
      </div>
      
  </section>

<!-- {% for work in list %}
<div class="users-block">
  <div class="user">
  <div class="photo"><img src="{{work.photo.url}}" alt="{{work.name}}"></div>
  </div>
  <div class="rest-card__headline card__name"> 
    <a href="/work/{{work.id}}" class="text-dark">{{work.name}}</a>
  </div>
     
  <div class="rest-card__description card__descr">
    <div class="rest-card__text">{{work.text}}</div>
    <div class="rest-card__rating">
        <p id="{{work.id}}"
          {% for like in likes %}{% if like.work.id == work.id %}class="like-added"
          {% endif %}{% endfor %}><i class="fas fa-heart" {% if user.is_staff %} onclick="like(this)"{% endif %}>***</i> <span class="mark">{{work.mark}}</span></p>
        </div>
  </div>
</div>
{% endfor %}
-->

{% endblock %}

mysite/work/templates/work/create.html
{% extends "mainApp/wrapper.html" %}

{% block title %}
Новое произведение
{% endblock %}

{% block content %}
<div class="outer-block events-block">
		<form action="/work/create/" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if not user.is_authenticated %}
        <p><label for="id_fio">ФИО:</label> <input type="text" name="fio" maxlength="50" required="" id="id_fio"></p>
        {% endif %}
        <input class="register__btn btn" type="submit" value="Создать">
		</form>
</div>
{% endblock %}

mysite/work/templates/work/work.html
{% extends "mainApp/wrapper.html" %}

{% block title %}
Произведение
{% endblock %}

{% block content %}
{% if error %}
<p>Такого мероприятия нет</p>
{% else %}

<section class="art-page width-limit">
    <img src="{{work.photo.url}}" alt="{{work.name}}" class="art-page__image">
    
    <div class="art-page__descr">
        <h1 class="art-page__name">{{work.name}}
            <div class="art-page__rating">
                <p id="{{work.id}}" {% for like in likes %}{% if like.work.id == work.id %}class="like-added" {% endif %}{% endfor %}><i class="fas fa-heart"  onclick="like(this)" ></i> <span class="mark">{{work.mark}}</span></p>
            </div>
        </h1>
        <p class="art-page__text">{{work.text}}</p>
        {% if work.extension == "video" %}
        <video controls name="media">
            <source src="{{work.document.url}}" type="video/webm"></video>
        {% elif work.extension == "audio" %}
        <audio controls src="{{work.document.url}}"></audio>
        {% elif work.extension != "none"%}
        <p><a href="{{work.document.url}}" target="_blank">Просмотр работы</a></p>
        {% endif %}
    </div>

</section>

<!-- <div class="outer-block events-block">
    <div class="container">
        <div class="event">
            <h1>{{work.name}}</h1>
            <img src="{{work.photo.url}}" alt="">
            <p>{{work.text}}</p>
            {% if work.extension == "video" %}
            <video controls  name="media"><source src="{{work.document.url}}" type="video/webm"></video>
            {% elif work.extension == "audio" %}
            <audio controls src="{{work.document.url}}"></audio>
            {% elif work.extension != "none"%}
            <p><a href="{{work.document.url}}">Работа...</a></p>
            {% endif %}
            <div class="rest-card__rating">
                <p id="{{work.id}}"
                    {% for like in likes %}{% if like.work.id == work.id %}class="like-added"
                    {% endif %}{% endfor %}><i class="fas fa-heart" {% if user.is_staff %} onclick="like(this)"{% endif %}>***</i> <span class="mark">{{work.mark}}</span></p>
            </div>
        </div>
    </div>
</div> -->
{% endif %}
{% endblock %}